'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/auth-context';
import { getCaseById, updateCase, resolveCase, getCasesFromStorage, saveCasesToStorage } from '@/lib/mock-data';
import { Case, DRSeverity } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  AlertCircle,
  Loader2,
  FileText,
  CheckCircle2,
  BarChart3,
  Download,
  ArrowLeft,
  Zap,
  Info,
} from 'lucide-react';

export default function CaseDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const router = useRouter();
  const { token } = useAuth();
  const [id, setId] = useState('');
  const [caseData, setCaseData] = useState<Case | null>(null);
  const [loading, setLoading] = useState(true);
  const [predicting, setPredicting] = useState(false);
  const [generatingReport, setGeneratingReport] = useState(false);
  const [resolving, setResolving] = useState(false);
  const [error, setError] = useState('');
  const [successMsg, setSuccessMsg] = useState('');

  useEffect(() => {
    params.then((p) => setId(p.id));
  }, [params]);

  useEffect(() => {
    if (!id) return;

    // Load case from mock storage
    const caseInfo = getCaseById(id);
    if (!caseInfo) {
      setError('Case not found');
    } else {
      setCaseData(caseInfo);
    }
    setLoading(false);
  }, [id]);

  const handlePrediction = async () => {
    if (!caseData) return;

    setPredicting(true);
    setError('');
    setSuccessMsg('');

    try {
      // Simulate AI prediction
      await new Promise(resolve => setTimeout(resolve, 2000));

      const DR_SEVERITIES: DRSeverity[] = ['None', 'Mild', 'Moderate', 'Severe', 'Proliferative'];
      const seed = parseInt(caseData.id.split('_')[1]) || 0;
      const randomValue = (seed * 9301 + 49297) % 233280;
      const index = Math.floor((randomValue / 233280) * DR_SEVERITIES.length);
      const severity = DR_SEVERITIES[index] || 'Mild';
      const confidence = 0.75 + (randomValue % 25) / 100;

      const updatedCase = updateCase(caseData.id, {
        prediction: severity,
        confidence: Math.min(0.99, confidence),
        status: 'In Progress',
      });

      if (updatedCase) {
        setCaseData(updatedCase);
        setSuccessMsg('Prediction completed successfully!');
      }
    } catch (err) {
      setError('Failed to run prediction');
      console.error(err);
    } finally {
      setPredicting(false);
    }
  };

  const handleGenerateReport = async () => {
    if (!caseData) return;

    setGeneratingReport(true);
    setError('');
    setSuccessMsg('');

    try {
      // Simulate report generation
      await new Promise(resolve => setTimeout(resolve, 1500));

      const reportContent = `
DIABETIC RETINOPATHY SCREENING REPORT
=====================================

Case ID: ${caseData.id}
Generated: ${new Date().toISOString()}

PATIENT INFORMATION
-------------------
Name: ${caseData.patient_name}
Age: ${caseData.age}
Gender: ${caseData.gender === 'M' ? 'Male' : 'Female'}

CLINICAL FINDINGS
-----------------
Diagnosis: ${caseData.prediction || 'Pending'}
Confidence: ${(caseData.confidence ? caseData.confidence * 100 : 0).toFixed(1)}%

ASSESSMENT
----------
This automated analysis indicates ${caseData.prediction?.toLowerCase() || 'pending'} diabetic retinopathy.
Please consult with an ophthalmologist for clinical confirmation and treatment planning.

DISCLAIMER
----------
This is an AI-assisted diagnostic tool. All findings require clinical verification by qualified healthcare professionals.

NEXT STEPS
----------
1. Review with ophthalmology specialist
2. Consider follow-up imaging if necessary
3. Document findings in patient record
4. Communicate results to referring physician

Generated by DR Screening Platform
      `.trim();

      setSuccessMsg('Report generated successfully!');
      
      // Download report as text file
      const element = document.createElement('a');
      element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(reportContent));
      element.setAttribute('download', `DR_Report_${caseData.id}.txt`);
      element.style.display = 'none';
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    } catch (err) {
      setError('Failed to generate report');
      console.error(err);
    } finally {
      setGeneratingReport(false);
    }
  };

  const handleResolve = async () => {
    if (!caseData) return;

    setResolving(true);
    setError('');
    setSuccessMsg('');

    try {
      const updatedCase = resolveCase(caseData.id);
      if (updatedCase) {
        setCaseData(updatedCase);
        setSuccessMsg('Case marked as resolved!');
        
        setTimeout(() => {
          router.push('/dashboard');
        }, 2000);
      }
    } catch (err) {
      setError('Failed to resolve case');
      console.error(err);
    } finally {
      setResolving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (!caseData) {
    return (
      <div className="flex-1 space-y-8 p-8">
        <Button variant="ghost" onClick={() => router.back()} className="mb-4 gap-2">
          <ArrowLeft className="w-4 h-4" />
          Back
        </Button>
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>{error || 'Case not found'}</AlertDescription>
        </Alert>
      </div>
    );
  }

  const severityColor: Record<string, string> = {
    None: 'bg-green-100 text-green-800 border-green-300',
    Mild: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    Moderate: 'bg-orange-100 text-orange-800 border-orange-300',
    Severe: 'bg-red-100 text-red-800 border-red-300',
    Proliferative: 'bg-red-200 text-red-900 border-red-400',
  };

  return (
    <div className="flex-1 space-y-8 p-8">
      {/* Header */}
      <div>
        <Button
          variant="ghost"
          onClick={() => router.back()}
          className="mb-4 gap-2 -ml-4"
        >
          <ArrowLeft className="w-4 h-4" />
          Back
        </Button>
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-foreground">Case Details</h1>
            <p className="text-muted-foreground mt-1">ID: {caseData.id}</p>
          </div>
          <Badge className={severityColor[caseData.prediction || 'None'] || 'bg-gray-100'}>
            {caseData.prediction || 'Pending'}
          </Badge>
        </div>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {successMsg && (
        <Alert className="border-green-500/30 bg-green-50 dark:bg-green-950">
          <CheckCircle2 className="h-4 w-4 text-green-600 dark:text-green-400" />
          <AlertDescription className="text-green-800 dark:text-green-200">
            {successMsg}
          </AlertDescription>
        </Alert>
      )}

      <div className="grid gap-6 md:grid-cols-3">
        {/* Patient Info */}
        <Card className="border-border/30 md:col-span-1">
          <CardHeader>
            <CardTitle className="text-lg">Patient Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-xs text-muted-foreground">Name</p>
              <p className="font-semibold text-foreground">{caseData.patient_name}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Age</p>
              <p className="font-semibold text-foreground">{caseData.age}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Gender</p>
              <p className="font-semibold text-foreground">{caseData.gender === 'M' ? 'Male' : 'Female'}</p>
            </div>
            <div className="pt-2 border-t border-border/30">
              <p className="text-xs text-muted-foreground">Status</p>
              <Badge className="mt-2 bg-blue-100 text-blue-800">{caseData.status}</Badge>
            </div>
          </CardContent>
        </Card>

        {/* Retinal Image */}
        <Card className="border-border/30 md:col-span-2">
          <CardHeader>
            <CardTitle className="text-lg">Retinal Image</CardTitle>
            <CardDescription>Uploaded fundus photograph</CardDescription>
          </CardHeader>
          <CardContent>
            {caseData.image_path ? (
              <div className="relative w-full h-96 bg-black rounded-lg overflow-hidden">
                <img
                  src={caseData.image_path}
                  alt="Retinal image"
                  className="w-full h-full object-contain"
                  onError={(e) => {
                    (e.target as HTMLImageElement).src =
                      'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="400" height="400"%3E%3Crect fill="%23333" width="400" height="400"/%3E%3Ctext fill="%23999" font-size="20" x="50%" y="50%" dominant-baseline="middle" text-anchor="middle"%3EImage not available%3C/text%3E%3C/svg%3E';
                  }}
                />
              </div>
            ) : (
              <div className="w-full h-96 bg-accent/10 rounded-lg flex items-center justify-center">
                <p className="text-muted-foreground">No image available</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Prediction Results */}
      <Card className="border-border/30">
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            <BarChart3 className="w-5 h-5" />
            AI Prediction Results
          </CardTitle>
          <CardDescription>Automated diabetic retinopathy screening results</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {caseData.prediction ? (
            <div className="space-y-4">
              <div className="grid gap-4 md:grid-cols-2">
                <div className="space-y-2">
                  <p className="text-sm font-medium text-muted-foreground">Diagnosis</p>
                  <div className="flex items-center gap-3">
                    <Badge className={`text-lg px-4 py-2 ${severityColor[caseData.prediction] || ''}`}>
                      {caseData.prediction}
                    </Badge>
                  </div>
                </div>

                <div className="space-y-2">
                  <p className="text-sm font-medium text-muted-foreground">Confidence Score</p>
                  <div className="space-y-2">
                    <div className="flex items-baseline gap-2">
                      <p className="text-3xl font-bold text-primary">
                        {(caseData.confidence! * 100).toFixed(1)}%
                      </p>
                    </div>
                    <div className="w-full bg-border/30 rounded-full h-3 overflow-hidden">
                      <div
                        className="bg-gradient-to-r from-primary to-accent h-full transition-all duration-300"
                        style={{ width: `${caseData.confidence! * 100}%` }}
                      />
                    </div>
                  </div>
                </div>
              </div>

              <Alert className="border-info/30 bg-info/5">
                <Info className="h-4 w-4" />
                <AlertDescription>
                  This is an AI-assisted diagnosis. Always consult with an ophthalmologist for clinical decisions.
                </AlertDescription>
              </Alert>
            </div>
          ) : (
            <div className="text-center py-8 space-y-4">
              <Info className="w-12 h-12 mx-auto text-muted-foreground/30" />
              <p className="text-muted-foreground">No predictions yet. Click below to analyze the image.</p>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-border/30">
            {!caseData.prediction && (
              <Button
                onClick={handlePrediction}
                disabled={predicting}
                className="gap-2 bg-primary hover:bg-primary/90"
              >
                {predicting && <Loader2 className="h-4 w-4 animate-spin" />}
                {predicting ? 'Running Analysis...' : 'Run AI Analysis'}
              </Button>
            )}

            {caseData.prediction && (
              <>
                <Button
                  onClick={handleGenerateReport}
                  disabled={generatingReport}
                  variant="outline"
                  className="gap-2 border-border/30"
                >
                  {generatingReport && <Loader2 className="h-4 w-4 animate-spin" />}
                  {generatingReport ? 'Generating...' : (
                    <>
                      <Download className="w-4 h-4" />
                      Download Report
                    </>
                  )}
                </Button>

                {caseData.status !== 'Resolved' && (
                  <Button
                    onClick={handleResolve}
                    disabled={resolving}
                    className="gap-2 ml-auto bg-green-600 hover:bg-green-700"
                  >
                    {resolving && <Loader2 className="h-4 w-4 animate-spin" />}
                    {resolving ? 'Resolving...' : (
                      <>
                        <CheckCircle2 className="w-4 h-4" />
                        Mark as Resolved
                      </>
                    )}
                  </Button>
                )}
              </>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Case Timeline */}
      <Card className="border-border/30">
        <CardHeader>
          <CardTitle className="text-lg">Case Timeline</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-3">
            <TimelineItem label="Case Created" date={caseData.created_at} icon="📝" />
            {caseData.prediction && (
              <TimelineItem label="Analysis Completed" date={new Date().toISOString()} icon="✅" />
            )}
            {caseData.status === 'Resolved' && (
              <TimelineItem label="Case Resolved" date={caseData.resolved_at} icon="🏁" />
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function TimelineItem({
  label,
  date,
  icon,
}: {
  label: string;
  date?: string;
  icon: string;
}) {
  return (
    <div className="flex gap-4 items-start">
      <div className="text-2xl flex-shrink-0">{icon}</div>
      <div className="flex-1 pt-1">
        <p className="font-medium text-foreground">{label}</p>
        {date && (
          <p className="text-xs text-muted-foreground">
            {new Date(date).toLocaleString()}
          </p>
        )}
      </div>
    </div>
  );
}
