import { NextRequest, NextResponse } from 'next/server';
import { v4 as uuidv4 } from 'uuid';
import { getDb } from '@/lib/db-init';
import { verifyToken, extractTokenFromHeader } from '@/lib/auth';
import { ensureInitialized } from '@/lib/init-service';

function generateMockPDFContent(caseData: any): string {
  return `
DIABETIC RETINOPATHY SCREENING REPORT
======================================

Case ID: ${caseData.id}
Patient Name: ${caseData.patient_name}
Age: ${caseData.age}
Gender: ${caseData.gender}
Screening Date: ${new Date(caseData.created_at).toLocaleDateString()}

SCREENING RESULTS
=================

Diagnosis: ${caseData.prediction || 'Pending'}
Confidence Score: ${caseData.confidence ? (caseData.confidence * 100).toFixed(1) + '%' : 'N/A'}

CLINICAL FINDINGS
=================

Based on the automated AI analysis of the retinal image:

1. Microaneurysms: ${caseData.prediction === 'None' ? 'Not detected' : 'Present'}
2. Hemorrhages: ${['Moderate', 'Severe', 'Proliferative'].includes(caseData.prediction || '') ? 'Detected' : 'Not detected'}
3. Exudates: ${['Moderate', 'Severe', 'Proliferative'].includes(caseData.prediction || '') ? 'Present' : 'Absent'}
4. Neovascularization: ${caseData.prediction === 'Proliferative' ? 'Present' : 'Not detected'}

RECOMMENDATIONS
===============

${
  caseData.prediction === 'None'
    ? '- Continue regular screening annually\n- Maintain good glycemic control'
    : caseData.prediction === 'Mild'
    ? '- Follow-up screening in 12 months\n- Optimize blood sugar and blood pressure management'
    : caseData.prediction === 'Moderate'
    ? '- Schedule ophthalmology consultation\n- Intensify glucose and hypertension control'
    : '- Immediate ophthalmology referral required\n- Consider laser treatment or anti-VEGF therapy'
}

SIGNATURE
=========

Generated by DR Screening AI System
Report ID: ${uuidv4()}
Date: ${new Date().toLocaleDateString()}
`;
}

export async function POST(request: NextRequest) {
  try {
    await ensureInitialized();

    const authHeader = request.headers.get('authorization');
    const token = extractTokenFromHeader(authHeader);

    if (!token) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const user = verifyToken(token);
    if (!user) {
      return NextResponse.json(
        { success: false, error: 'Invalid token' },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { case_id } = body;

    if (!case_id) {
      return NextResponse.json(
        { success: false, error: 'case_id is required' },
        { status: 400 }
      );
    }

    const db = getDb();
    const caseData = db
      .prepare('SELECT * FROM cases WHERE id = ? AND doctor_id = ?')
      .get(case_id, user.id) as any;

    if (!caseData) {
      db.close();
      return NextResponse.json(
        { success: false, error: 'Case not found' },
        { status: 404 }
      );
    }

    // Check if report already exists
    const existingReport = db
      .prepare('SELECT * FROM reports WHERE case_id = ?')
      .get(case_id) as any;

    let reportId: string;
    let reportPath: string;

    if (existingReport) {
      reportId = existingReport.id;
      reportPath = existingReport.report_path;
    } else {
      reportId = 'report_' + Date.now();
      reportPath = `/reports/${uuidv4()}.txt`;

      // Insert report record
      db.prepare(`
        INSERT INTO reports (id, case_id, report_path, generated_at)
        VALUES (?, ?, ?, ?)
      `).run(reportId, case_id, reportPath, new Date().toISOString());
    }

    db.close();

    return NextResponse.json(
      {
        success: true,
        data: {
          report_id: reportId,
          report_path: reportPath,
          content: generateMockPDFContent(caseData),
        },
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('[API] Report generation error:', error);
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    );
  }
}
